import {contenedorBg, contenedorBgTwo, contenedorBgThree, contenedorBgFour, contenedorBgFive, contenedorBgSix, contenedorBgSeven, contenedorBgEight, contenedorBgNine, contenedorBgTen, contenedorBgEleven, contenedorBgTwelve, contenedorBgThirtenn, contenedorBgFourteen} from './js/cambiarBg.js';
import {openBtn, closeBtn, modal, contenedorModal} from './js/modal.js';

contenedorBg;
contenedorBgTwo;
contenedorBgThree;
contenedorBgFour;
contenedorBgFive;
contenedorBgSix;
contenedorBgSeven;
contenedorBgEight;
contenedorBgNine;
contenedorBgTen;
contenedorBgEleven;
contenedorBgTwelve;
contenedorBgThirtenn;
contenedorBgFourteen;
openBtn;
closeBtn;
modal;
contenedorModal;